# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"%\n\x07Opinion\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"E\n\x0f\x41nalysisRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12#\n\x08opinions\x18\x02 \x03(\x0b\x32\x11.analysis.Opinion\"u\n\x10\x41nalysisResponse\x12\r\n\x05topic\x18\x01 \x01(\t\x12&\n\x06groups\x18\x02 \x03(\x0b\x32\x16.analysis.OpinionGroup\x12\x12\n\nconclusion\x18\x03 \x01(\t\x12\x16\n\x0e\x66ormatted_text\x18\x04 \x01(\t\"E\n\x0cOpinionGroup\x12\x10\n\x08group_id\x18\x01 \x01(\t\x12#\n\x08opinions\x18\x02 \x03(\x0b\x32\x11.analysis.Opinion\"=\n\x16\x43lassifyOpinionRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x14\n\x0copinion_text\x18\x02 \x01(\t\";\n\x17\x43lassifyOpinionResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32\xb3\x01\n\x0f\x41nalysisService\x12H\n\x0f\x41nalyzeOpinions\x12\x19.analysis.AnalysisRequest\x1a\x1a.analysis.AnalysisResponse\x12V\n\x0f\x43lassifyOpinion\x12 .analysis.ClassifyOpinionRequest\x1a!.analysis.ClassifyOpinionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPINION']._serialized_start=28
  _globals['_OPINION']._serialized_end=65
  _globals['_ANALYSISREQUEST']._serialized_start=67
  _globals['_ANALYSISREQUEST']._serialized_end=136
  _globals['_ANALYSISRESPONSE']._serialized_start=138
  _globals['_ANALYSISRESPONSE']._serialized_end=255
  _globals['_OPINIONGROUP']._serialized_start=257
  _globals['_OPINIONGROUP']._serialized_end=326
  _globals['_CLASSIFYOPINIONREQUEST']._serialized_start=328
  _globals['_CLASSIFYOPINIONREQUEST']._serialized_end=389
  _globals['_CLASSIFYOPINIONRESPONSE']._serialized_start=391
  _globals['_CLASSIFYOPINIONRESPONSE']._serialized_end=450
  _globals['_ANALYSISSERVICE']._serialized_start=453
  _globals['_ANALYSISSERVICE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
